#!/bin/bash
if ! ./make.sh ; then
    echo "=============================================="
    echo "================ MAKE FAILED! ================"
    echo "=============================================="
    exit $?
fi

echo ""
echo ""

for f1 in input/*.fasta
do
    for f2 in input/*.fasta
    do
        if [ "$f1" == "$f2" ]
        then
            break
        fi
        ./build/bin/BioSeq_Project2 all ${f1} ${f2}
    done
done